// This configuration is automatically generated by Firebase Studio.
// Do not edit this file manually.
export const firebaseConfig = {
  "projectId": "studio-4898361166-80dfb",
  "appId": "1:723635950749:web:c14046f4ebcec92afab074",
  "apiKey": "AIzaSyD9T1nHlj55vFC2a3AYYrHbMAtLIy-5y98",
  "authDomain": "pharmentor.academy",
  "measurementId": "",
  "messagingSenderId": "723635950749"
};
